name: Test Permissions

on:
  workflow_dispatch:

jobs:
  test-permissions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Test git push permissions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Test"
        
        # Create a test file
        echo "Test file created at $(date)" > test-permissions.txt
        git add test-permissions.txt
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        # Commit and push
        git commit -m "test: Verify GitHub Actions permissions work"
        git push
        
        # Clean up test file
        git rm test-permissions.txt
        git commit -m "test: Clean up permissions test file"
        git push
